### ISSUE TITLE
Pinata is blocking view and triggered even when one isn't using Gathering Tools.

### ISSUE THREAD

**Issue by Omega1Felix** [Taschenbuch/BlishHud-GatheringTools#1]
The large icon showing up everytime you use any gathering tool in the centre of screen is annoying and unnecessary when you have equipped tools. It even show up when one pick up Unstable Bloodstone Fragments after killing those Bloodstone creatures in Bloodstone Fen.

In short it blocks view when one need to see what is going on in surrounding enviroment.

I appriate the work you have done for showing which character and where Gather Tools might be stored, but this issues is too big, at least for me, to make this any useful module to have enabled during game play.

**Comment by Taschenbuch** [comment]
There is no large icon popping up when you use gathering tools. The only large image i show, is when you press the logout key binding button. Do you mean this one?
![grafik](https://user-images.githubusercontent.com/43114787/185731749-78b1ca38-a3a6-41b2-8329-ecb66dc13187.png)

In this case you have changed the gw2 ingame interaction key from the default "F" to "F12", i guess? If yes, go to the gathering tools module settings and double click the right side of the key binding setting. Change it to your ingame logout key binding or completely unbind it:
 
![grafik](https://user-images.githubusercontent.com/43114787/185731834-c3378d63-b550-4a6c-b151-65761720046d.png)

if you have any further issues with this or other questions, feel free to ask here or in the Blish discord: discord.gg/blishhud. :)

**Comment by Omega1Felix** [comment]
Thanks for your help!

I didn't see that you could both change size on that text and that Choya holding gathering tools. I could remove that with turning slider to left (zero) for size, so that helped and position text in the upper center of screen in case it would be triggered during some fight by forgetting which keybinds that have been set up.

As for keybind I had set up (ALT + F12) for Interact to free up "F" key for movement. So it is easy to trigger modules keybind when layer one can work at same time as layer two (ALT key as modifier combined or as by itself act out a command).

Anyway thanks for your help again!

It solved my problem and made me scroll down more on Settings for this module to find that there where section I might not have been seeing first time when I set up this add on.

**Comment by Taschenbuch** [comment]
Option1:
if i understand you correctly, you have no use for this reminder on F12 at all. So the better solution in your case is to unbind the Logout key, as described in the screenshot above. then the module will not show anything when when you press F12. This keybinding in the module setting is only used by the module itself. 

Option 2:
OR you could change your logout keybinding, if you do not use the logout button (F12) anyway. set it in the gw2 ingame keybind settings to something else like F11 (?) and change it in the module settings to F11 too.

Option 3:
another way, but unnecessaryly complex compared to Optioon 1 and 2, would be this:
"reminder text": remove the text
"show reminder background" uncheck this
"show image in reminder" uncheck this
"additional reminder hint" uncheck this.

WARNING:
Beaware of this setting, as it will affect modules like Pathing. You may wanna set your "Alt + F12" keybinding here too, to get no issues with other modules:
![grafik](https://user-images.githubusercontent.com/43114787/185778266-05f97127-edd5-4f0e-a07d-a64268e18b33.png)
